theme = "dark_plus"

[keys.normal]
"`" = "switch_to_uppercase"
"´" = "switch_to_lowercase"
"A-j" = [
  "extend_to_line_bounds",
  "delete_selection",
  "paste_after",
  "select_mode",
  "goto_line_start",
  "normal_mode",
] # Move line(s) down
"A-k" = [
  "extend_to_line_bounds",
  "delete_selection",
  "move_line_up",
  "paste_before",
  "flip_selections",
] # Move line(s) up

[editor.auto-save]
after-delay.enable = true
after-delay.timeout = 300

[editor.file-picker]
hidden = false

[editor.lsp]
display-inlay-hints = true

